export const APP_CONFIG = {
  pageTitle: "Nosso Novo Capítulo",
  pageSubtitle: "Lista de casa nova",
  description:
    "Estamos começando uma fase nova e queremos dividir esse momento com pessoas especiais. Se quiser nos presentear, escolha um item da lista abaixo. Assim conseguimos organizar tudo sem repetir presentes.",
  ownerEmails: ["emillepatricia.d@hotmail.com"],
};

// Cole aqui as credenciais do app Web que o Firebase gera para você.
// Esse objeto pode ficar no front-end. A segurança real fica nas regras do Firestore.
export const firebaseConfig = {
  apiKey: "AIzaSyDw9280wUt2mCefehb9zehEVTP1HJnxkoc",
  authDomain: "casa-nova-novo-capitulo.firebaseapp.com",
  projectId: "casa-nova-novo-capitulo",
  storageBucket: "casa-nova-novo-capitulo.firebasestorage.app",
  messagingSenderId: "232209099209",
  appId: "1:232209099209:web:7f1b38360273765f226018",
  measurementId: "G-KRLMKKYG62",
};

export const CATEGORIES = [
  { id: "todos", label: "Todos", icon: "✨" },
  { id: "cozinha", label: "Cozinha", icon: "🍳" },
  { id: "sala", label: "Sala", icon: "🛋️" },
  { id: "quarto", label: "Quarto", icon: "🛏️" },
  { id: "banheiro", label: "Banheiro", icon: "🛁" },
  { id: "lavanderia", label: "Lavanderia", icon: "🧺" },
  { id: "decoracao", label: "Decoração", icon: "🪴" },
  { id: "outros", label: "Outros", icon: "🎁" },
];

export const INITIAL_ITEMS = [
  {
    id: "jogo-copos",
    title: "Jogo de copos",
    category: "cozinha",
    description: "Sugestão: 6 unidades.",
    icon: "🥛",
    order: 1,
  },
  {
    id: "potes-organizadores",
    title: "Potes organizadores",
    category: "cozinha",
    description: "Para mantimentos, marmitas ou organização.",
    icon: "🫙",
    order: 2,
  },
  {
    id: "escorredor-louca",
    title: "Escorredor de louça",
    category: "cozinha",
    description: "Item básico e muito útil no dia a dia.",
    icon: "🍽️",
    order: 3,
  },
  {
    id: "tabua-corte",
    title: "Tábua de corte",
    category: "cozinha",
    description: "Pode ser madeira, bambu ou plástico resistente.",
    icon: "🔪",
    order: 4,
  },
  {
    id: "panos-prato",
    title: "Kit panos de prato",
    category: "cozinha",
    description: "Sugestão: kit com 3 ou mais unidades.",
    icon: "🧻",
    order: 5,
  },
  {
    id: "porta-utensilios",
    title: "Porta utensílios",
    category: "cozinha",
    description: "Para colher, concha, espátula e afins.",
    icon: "🥄",
    order: 6,
  },
  {
    id: "jogo-americano",
    title: "Jogo americano",
    category: "cozinha",
    description: "Para deixar a mesa mais bonita.",
    icon: "🍴",
    order: 7,
  },
  {
    id: "forma-bolo",
    title: "Forma de bolo",
    category: "cozinha",
    description: "Redonda, retangular ou antiaderente.",
    icon: "🍰",
    order: 8,
  },
  {
    id: "almofadas",
    title: "Almofadas",
    category: "sala",
    description: "Cores neutras ou tons aconchegantes.",
    icon: "🧸",
    order: 9,
  },
  {
    id: "manta-sofa",
    title: "Manta para sofá",
    category: "sala",
    description: "Para deixar a sala mais acolhedora.",
    icon: "🧶",
    order: 10,
  },
  {
    id: "aromatizador",
    title: "Aromatizador",
    category: "sala",
    description: "Cheirinho de casa nova sempre ajuda.",
    icon: "🕯️",
    order: 11,
  },
  {
    id: "porta-retrato",
    title: "Porta-retrato",
    category: "sala",
    description: "Para guardar memórias dessa fase.",
    icon: "🖼️",
    order: 12,
  },
  {
    id: "jogo-lencol",
    title: "Jogo de lençol",
    category: "quarto",
    description: "Verificar tamanho da cama antes de comprar.",
    icon: "🛌",
    order: 13,
  },
  {
    id: "cabides",
    title: "Cabides",
    category: "quarto",
    description: "Nunca é demais em casa nova.",
    icon: "👕",
    order: 14,
  },
  {
    id: "organizador-gaveta",
    title: "Organizador de gaveta",
    category: "quarto",
    description: "Para roupas, acessórios e miudezas.",
    icon: "🗂️",
    order: 15,
  },
  {
    id: "jogo-toalhas",
    title: "Jogo de toalhas",
    category: "banheiro",
    description: "Banho e rosto, em tons neutros.",
    icon: "🧖",
    order: 16,
  },
  {
    id: "tapete-banheiro",
    title: "Tapete de banheiro",
    category: "banheiro",
    description: "Antiderrapante de preferência.",
    icon: "🛁",
    order: 17,
  },
  {
    id: "saboneteira",
    title: "Kit saboneteira",
    category: "banheiro",
    description: "Saboneteira, porta-escova ou dispenser.",
    icon: "🧼",
    order: 18,
  },
  {
    id: "cesto-roupa",
    title: "Cesto de roupa",
    category: "lavanderia",
    description: "Dobrável, de tecido ou plástico.",
    icon: "🧺",
    order: 19,
  },
  {
    id: "varal-chao",
    title: "Varal de chão",
    category: "lavanderia",
    description: "Ajuda muito em apartamento ou casa pequena.",
    icon: "👚",
    order: 20,
  },
  {
    id: "kit-limpeza",
    title: "Kit limpeza",
    category: "lavanderia",
    description: "Panos, esponjas, luvas e itens básicos.",
    icon: "🧽",
    order: 21,
  },
  {
    id: "plantinha",
    title: "Plantinha",
    category: "decoracao",
    description: "Suculenta, jiboia, espada-de-são-jorge ou similar.",
    icon: "🪴",
    order: 22,
  },
  {
    id: "vaso-decorativo",
    title: "Vaso decorativo",
    category: "decoracao",
    description: "Pequeno ou médio, para mesa ou aparador.",
    icon: "🏺",
    order: 23,
  },
  {
    id: "luminaria",
    title: "Luminária pequena",
    category: "decoracao",
    description: "Para criar um cantinho aconchegante.",
    icon: "💡",
    order: 24,
  },
  {
    id: "vale-presente",
    title: "Vale-presente",
    category: "outros",
    description: "Para ajudar com algum detalhe que faltar.",
    icon: "💌",
    order: 25,
  },
];
